import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {children}
                <div className="bg-gray-100 bg-yellow-100 bg-orange-100 bg-red-100 bg-green-100 bg-blue-100 bg-purple-100 hidden"></div>
                <div className="text-gray-800 text-yellow-800 text-orange-800 text-red-800 text-green-800 text-blue-800 text-purple-800 hidden"></div>
            </body>
        </html>
    );
}
